//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PegAEsys.rc
//
#define IDT_TRAP                        0
#define IDOK3                           2
#define ID_LOAD_JB2                     2
#define IDOK2                           3
#define IDC_TRACING_SOLO                3
#define IDC_TRANSPEN_APPLY              3
#define IDSKIPALL                       3
#define ID_NEW_JB2                      3
#define ID_SAVE_JB2                     3
#define ID_APPLY                        3
#define ID_SET_EXTENT                   4
#define IDC_TRANSTYLE_APPLY             4
#define ID_SET_ORIGIN                   5
#define ID_LOAD_JB3                     6
#define ID_ADD_BORDER                   6
#define ID_NEW_JB3                      7
#define ID_REMOVE_BORDER                7
#define ID_NEWJB2                       8
#define ID_LOAD_JB4                     9
#define ID_SAVEAS_JB2                   9
#define IDR_MAINFRAME                   101
#define IDR_LAYER                       102
#define IDR_WINDOW                      103
#define IDR_TRAP                        104
#define IDR_PEGSTROKEFONT               105
#define IDD_ABOUTBOX                    111
#define IDD_PASTE_POSITION              113
#define IDD_GET_LAYER_NAME              116
#define IDD_FILE_MANAGE                 118
#define IDD_ADD_NOTE                    119
#define IDD_VIEW_ZOOM                   121
#define IDD_SUBPROC_PIPE_SYMBOL         127
#define IDD_PROJ_OBLIQUE                131
#define IDD_PROJ_AXONOMETRIC            132
#define IDD_PROJ_ISOMETRIC              133
#define IDD_PROJ_PERSPECTIVE            134
#define IDD_TRACING_EX                  135
#define IDD_TRACING_PATH                135
#define IDD_ANNOTATE_ENTER_TEXT         139
#define IDD_HOME_POINT_EDIT             143
#define IDD_TRAP_MODIFY                 146
#define IDD_HOME_POINT_GO               147
#define IDD_TRAP_FILTER                 148
#define IDD_VIEWLIGHTING                150
#define IDD_VIEW_LIGHTING               150
#define IDD_PRINTABORT                  151
#define IDD_INSERT_BLOCK                152
#define IDR_MENU1                       153
#define IDR_TRACING                     153
#define IDC_CURSOR1                     156
#define IDC_CURSOR2                     157
#define IDC_BLANK                       157
#define IDD_FILE_IMPORT                 158
#define IDD_SETUP_IMPORT                158
#define IDD_DIALOG1                     160
#define IDD_EDIT_TRAPCOMMANDS_QUERY2    160
#define IDD_EDIT_TRAPCOMMANDS_QUERY     160
#define IDD_FILE_CLEAN                  161
#define IDD_OPTIONS_TABS_MAIN           162
#define IDD_TAB_PEN                     163
#define IDD_OPTIONS_TAB_NOTE            164
#define IDD_OPTIONS_TAB_IMPORT          165
#define IDD_DIALOG2                     166
#define IDD_OPTIONS_TAB_CONSTRAINTS     168
#define IDD_OPTIONS_TAB_DIMHATCH        169
#define IDD_OPTIONS_TAB_DIMENSION       169
#define IDD_TAB_SEVEN                   170
#define IDD_PRINTPREVIEW                170
#define IDD_TAB_SEVEN1                  171
#define IDD_TAB_EIGHT                   171
#define IDD_TRACING_INCLUDE             172
#define IDD_TAB9                        173
#define IDD_OPTIONS_TAB_SCROLLMOUSE     173
#define IDD_OPTIONS_TAB_SCROLLBARS      173
#define IDD_SETUP_TABS_MAIN             174
#define IDD_SETUP_TABS_MAIN2            174
#define IDD_SETUP_TAB_PEN               175
#define IDD_SETUP_TAB_DRAW              176
#define IDD_SETUP_TAB_LPD               177
#define IDD_SETUP_TAB_RLPD              178
#define IDD_SETUP_TAB_PIPE              179
#define IDD_SETUP_TAB_DRAW2             180
#define IDD_SETUP_TAB_ANNOTATE          181
#define IDD_SETUP_TAB_EDIT              182
#define IDD_SETUP_TAB_FIXUP             183
#define IDD_TRACING_INCLUDE1            184
#define IDD_BITMAP_OPEN                 184
#define IDD_TRANSLATE_PENS              185
#define IDR_TOOLBAR1                    186
#define IDD_ARCHIVE                     189
#define IDD_INVALID_PRIM                190
#define IDD_FILE_OPEN                   191
#define IDD_FILE_SAVEAS                 192
#define IDD_FILE_OPEN1                  193
#define IDD_ACADSELECT                  194
#define IDD_DIALOG3                     195
#define IDB_ODOM                        196
#define IDB_BITMAP2                     197
#define IDD_PLOTPREVIEW                 198
#define IDD_PROFILE_MANAGER             199
#define IDD_PROGRESS                    200
#define IDD_PROGRESS_DIALOG             200
#define IDD_OPTIONS_TAB_NOTE1           201
#define IDD_OPTIONS_TAB_VIEW            202
#define IDD_OPTIONS_TAB_USERAXIS        203
#define IDD_OPTIONS_TAB_HATCH           204
#define IDD_OPTIONS_TAB_SCALE           205
#define IDD_OPTIONS_TAB_MOUSE           206
#define IDD_OPTIONS_TAB_REGISTRY        207
#define IDD_OPTIONS_TAB_UNITS           208
#define IDD_DIALOG4                     209
#define IDB_BITMAP3                     210
#define IDD_OPTIONS_TABS_MAIN1          210
#define IDB_BITMAP4                     211
#define IDD_GENERAL_APPEARANCE          211
#define IDD_GENERAL_PROFILES            212
#define IDD_SETUP_TABS_MAIN1            213
#define IDD_PROJ_ISOMETRIC2             214
#define IDD_TEXT_PASTE                  215
#define IDD_PROJ_MAIN                   216
#define IDD_PROJ_AXONOMETRIC2           217
#define IDD_PROJ_OBLIQUE2               218
#define IDD_PROJ_PERSPECTIVE2           219
#define IDD_STATE_BUTTON                220
#define IDD_OPTIONS_TAB_IMPORT1         221
#define IDD_SOLOSTATE_BUTTON            222
#define IDD_OPTIONS_TAB_NOTE2           223
#define IDD_FILE_MANAGE1                224
#define IDD_PROGRESS_DIALOG1            225
#define IDD_FILE_MANAGE2                226
#define IDD_FILE_MANAGE3                227
#define IDD_GET_LAYER_COLOR             228
#define IDD_SETUP_IMPORT1               229
#define IDD_IMPORT_REPORT               230
#define IDD_BITMAP_EDIT                 231
#define IDD_BACKGROUND_MODE             232
#define IDD_SETUP_TAB_DIMENSION         233
#define IDD_ACADEXPORT                  234
#define IDC_VIEW_ISO_LEFT               1001
#define IDC_VIEW_ISO_RIGHT              1002
#define IDC_VIEW_ISO_FRONT              1003
#define IDC_VIEW_ISO_BACK               1004
#define IDC_VIEW_ISO_ABOVE              1005
#define IDC_VIEW_ISO_UNDER              1006
#define IDC_ANG                         1007
#define IDC_APPS                        1008
#define IDC_X                           1010
#define IDC_Y                           1011
#define IDC_Z                           1012
#define IDC_FIL_AREA_HAT_ID             1021
#define IDC_FIL_AREA_HAT_X_SCAL         1022
#define IDC_FIL_AREA_HAT_Y_SCAL         1023
#define IDC_FIL_AREA_HAT_ROT_ANG        1025
#define IDC_WIDTH                       1029
#define IDC_DEPTH                       1030
#define IDC_LEFT                        1031
#define IDC_CENTER                      1032
#define IDC_RIGHT                       1033
#define IDC_MITERED                     1034
#define IDC_RADIAL                      1035
#define IDC_GEN_VANES                   1036
#define IDC_RADIUS_FACTOR               1037
#define IDC_BEST                        1039
#define IDC_RADIUS_FACTOR2              1047
#define IDC_VIEW_VPN_Z_ANG              1048
#define IDC_LEFT2                       1048
#define IDC_VIEW_VPN_X_ANG              1049
#define IDC_CENTER2                     1049
#define IDC_RIGHT2                      1050
#define IDC_VIEW_DOP_Z_ANG              1052
#define IDC_VIEW_DOP_X_ANG              1053
#define IDC_VIEW_DIS_TO_TARGET          1054
#define IDC_FIX_SIZ                     1057
#define IDC_FIX_AX_TOL                  1058
#define IDC_USR_AX_INF_ANG              1063
#define IDC_USR_AX_Z_OFF_ANG            1064
#define IDC_USR_GRID_X_INT              1068
#define IDC_USR_GRID_Y_INT              1069
#define IDC_USR_GRID_Z_INT              1070
#define IDC_GRID_DOT_INT_X              1074
#define IDC_GRID_DOT_INT_Y              1075
#define IDC_GRID_DOT_INT_Z              1076
#define IDC_GRID_LN_INT_X               1077
#define IDC_GRID_LN_INT_Y               1078
#define IDC_GRID_LN_INT_Z               1079
#define IDC_GRID_PTS_DIS_ON             1080
#define IDC_GRID_LNS_DIS_ON             1081
#define IDC_GRID_SNAP_ON                1082
#define IDC_PROFILE                     1083
#define IDC_GEOMETRY_LIST               1087
#define IDC_DRWG_REP_DEL                1094
#define IDC_ANN_BUB_RAD                 1099
#define IDC_ANN_BUB_FACETS              1100
#define IDC_ANN_DEF_TXT                 1101
#define IDC_ANN_HOOK_RAD                1102
#define IDC_ANN_GAP_SPACE_FAC           1103
#define IDC_ANN_ARR_SIZ                 1104
#define IDC_ANN_ARR_TYP                 1105
#define IDC_COL_LIST                    1106
#define IDC_MORELESS                    1115
#define IDC_LAST                        1116
#define IDC_VIEW_NAME_LIST              1121
#define IDC_KEYPLAN_AREA                1124
#define IDC_LESS_AREA                   1125
#define IDC_SAVE                        1127
#define IDC_RECALL                      1128
#define IDC_LAY                         1138
#define IDC_DIR_LIST                    1149
#define IDC_METRIC_UNITS                1155
#define IDC_EDIT_OP_SIZING              1166
#define IDC_EDIT_OP_ROTATION            1167
#define IDC_EDIT_OP_MIRRORING           1168
#define IDC_EDIT_OP_SIZ_X               1171
#define IDC_EDIT_OP_SIZ_Y               1172
#define IDC_EDIT_OP_SIZ_Z               1173
#define IDC_EDIT_OP_ROT_X               1174
#define IDC_EDIT_OP_ROT_Y               1175
#define IDC_EDIT_OP_ROT_Z               1176
#define IDC_VERNIER_SIZE                1177
#define IDC_EDIT_OP_MIR_X               1178
#define IDC_EDIT_OP_MIR_Y               1179
#define IDC_EDIT_OP_MIR_Z               1180
#define IDC_VERNIER_ROT                 1181
#define IDC_TRAP_FILTER_PEN             1185
#define IDC_TRAP_FILTER_LINE            1186
#define IDC_TRAP_FILTER_ELEMENT         1187
#define IDC_TRAP_FILTER_PEN_ID          1188
#define IDC_TRAP_FILTER_ELEMENT_LIST    1190
#define IDC_SCALE                       1191
#define IDC_TRAP_FILTER_LINE_LIST       1192
#define IDC_NEAR                        1208
#define IDC_FAR                         1209
#define IDC_LIGHT_AMBIENT_RED           1210
#define IDC_L0_AMBIENT_RED              1211
#define IDC_L0_POSITION_X               1212
#define IDC_L0_POSITION_Z               1213
#define IDC_LIGHT_AMBIENT_GREEN         1214
#define IDC_LIGHT_AMBIENT_BLUE          1215
#define IDC_L0_AMBIENT_GREEN            1216
#define IDC_L0_AMBIENT_BLUE             1217
#define IDC_L0_SPECULAR_RED             1218
#define IDC_L0_SPECULAR_GREEN           1219
#define IDC_L0_SPECULAR_BLUE            1220
#define IDC_L0_DIFFUSE_RED              1221
#define IDC_L0_DIFFUSE_GREEN            1222
#define IDC_L0_DIFFUSE_BLUE             1223
#define IDC_FILL                        1230
#define IDC_CONSTRAINTS                 1231
#define IDC_SCALE2                      1231
#define IDC_TRACLOAK                    1239
#define IDC_TRAFUSE                     1241
#define IDC_LAYDELETE                   1242
#define IDC_LAYMELT                     1243
#define IDC_LAY_XLATE                   1244
#define IDC_L0_POSITION_Y               1245
#define IDC_LAY_ACTIVEALL               1245
#define IDC_LAY_STATICALL               1246
#define IDC_LAY_HIDDENALL               1247
#define IDC_TRA                         1248
#define IDC_TRA_MAPALL                  1248
#define IDC_LAYRENAME                   1249
#define IDC_TRAEXCLUDE                  1250
#define IDC_TRAINCLUDE                  1251
#define IDC_LAYNEW                      1252
#define IDC_PENSTYLE                    1253
#define IDC_COLOR_ID                    1254
#define IDC_TRA_VIEWALL                 1255
#define IDC_SEGS                        1256
#define IDC_TRA_CLOAKALL                1257
#define IDC_LAYWORK                     1263
#define IDC_LAYACTIVE                   1264
#define IDC_LEFT_DOWN                   1273
#define IDC_EDIT1                       1274
#define IDC_LEFT_DOWN2                  1274
#define IDC_SCROLL_HSIZE                1274
#define IDC_INFL_ANGLE                  1274
#define IDC_MOVE_LAYNAME                1274
#define IDC_MARGIN_X                    1274
#define IDC_JB2_FILE                    1274
#define IDC_WIDTHCOUNT                  1274
#define IDC_EDIT_X                      1274
#define IDC_EDIT2                       1275
#define IDC_MARGIN_Y                    1275
#define IDC_MARGIN_X2                   1275
#define IDC_EDIT_Y                      1275
#define IDC_LEFT_UP                     1276
#define IDC_MARGIN_Y2                   1276
#define IDC_EDIT_Y2                     1276
#define IDC_EDIT_WIDTH                  1276
#define IDC_RIGHT_DOWN                  1277
#define IDC_MARGIN_X3                   1277
#define IDC_RIGHT_UP                    1278
#define IDC_ARC_3_POINT                 1278
#define IDC_MARGIN_Y3                   1278
#define IDC_ARC_CENTER_2_POINTS         1279
#define IDC_LEFT_UP2                    1279
#define IDC_SCROLL_HSENS                1279
#define IDC_CURVE_SPLINE                1280
#define IDC_RIGHT_DOWN2                 1280
#define IDC_SCROLL_VSIZE                1280
#define IDC_CURVE_FITTED                1281
#define IDC_RIGHT_UP2                   1281
#define IDC_SCROLL_VSENS                1281
#define IDC_MARKER_TYPE                 1282
#define IDC_PEN                         1283
#define IDC_LINE                        1284
#define IDC_NAME                        1285
#define IDC_MOD_FILL                    1292
#define IDC_MOD_PEN                     1293
#define IDC_MOD_LINE                    1294
#define IDC_MOD_NOTE                    1295
#define IDC_MOD_MARKER                  1296
#define IDC_LAYSTATIC                   1298
#define IDC_UP_ONE_LEVEL                1299
#define IDC_TRAOPEN                     1300
#define IDC_TRAMAP                      1302
#define IDC_TRAVIEW                     1304
#define IDC_LAYHIDDEN                   1305
#define IDC_FILE_NAME                   1307
#define IDC_NEW_FOLDER                  1308
#define IDC_DESCRIPTION                 1310
#define IDC_LAYER_PREVIEW               1312
#define IDC_SOLO                        1314
#define IDC_BLOCKS_LIST                 1315
#define IDC_REFERENCES                  1316
#define IDC_SOLO2                       1317
#define IDC_UNBLOCK                     1317
#define IDC_UNBLOCK_SELECTED            1317
#define IDC_UNBLOCK_ALL                 1318
#define IDC_CHECK1                      1319
#define IDC_FUSE_ALL                    1319
#define IDC_DISP_LAYER_TEXT             1319
#define IDC_DISP_MODE                   1319
#define IDC_IMPORT_EXPLODE              1319
#define IDC_VECTORIZETEXT               1319
#define IDC_APPEND                      1320
#define IDC_INSERT                      1320
#define IDC_CLEAN_BLOCKS                1320
#define IDC_TASK_ANNOTATE               1320
#define IDC_CHECK2                      1320
#define IDC_DISP_LAYER_TEXT2            1320
#define IDC_IMPORT_VIEWBOX              1320
#define IDC_CLEAN_LAYERS                1321
#define IDC_TASK_PIPE                   1321
#define IDC_CHECK3                      1321
#define IDC_IMPORT_VIEWPORT             1321
#define IDC_CLEAN_DUPL                  1322
#define IDC_TASK_PENS                   1322
#define IDC_CHECK4                      1322
#define IDC_PRINT_MARKERS               1322
#define IDC_RADIO1                      1323
#define IDC_CLEAN_NOTES                 1323
#define IDC_TASK_DRAW2                  1323
#define IDC_CIRCLE_CR                   1323
#define IDC_SHEET_FULL                  1323
#define IDC_CHECK5                      1323
#define IDC_DISP_STATUS                 1323
#define IDC_PRIM_VECTORIZE              1323
#define IDC_BITMAP_LOCKED               1323
#define IDC_RADIO2                      1324
#define IDC_CLEAN_SEGS                  1324
#define IDC_TASK_LPD                    1324
#define IDC_CIRCLE_DIAM                 1324
#define IDC_SHEET_HALF                  1324
#define IDC_CHECK6                      1324
#define IDC_PENWIDTHS                   1324
#define IDC_PRIM_DATA                   1324
#define IDC_BITMAP_UNLOCKED             1324
#define IDC_FILL_PATTERN                1325
#define IDC_FLAT_IRON                   1325
#define IDC_TASK_FIXUP                  1325
#define IDC_SHEET_QUARTER               1325
#define IDC_RADIO3                      1325
#define IDC_CHECK7                      1325
#define IDC_DISP_ORIGIN                 1325
#define IDC_PURGE                       1326
#define IDC_TASK_RLPD                   1326
#define IDC_MOVE_ZERO                   1326
#define IDC_GET                         1327
#define IDC_TASK_EDIT                   1327
#define IDC_TASK_DRAW                   1328
#define IDC_FILES_EX                    1329
#define IDC_BLOCKS                      1330
#define IDC_LOAD                        1331
#define IDC_DISTANCE                    1332
#define IDC_LIST                        1334
#define IDC_TIC_SIZE                    1335
#define IDC_RISEDROP_RADIUS             1336
#define IDC_OPTIONS_ALL                 1339
#define IDC_OPT_UNITS                   1340
#define IDC_OPT_HATCH                   1341
#define IDC_OPT_VIEW                    1342
#define IDC_OPT_NOTE                    1343
#define IDC_OPT_DIM                     1344
#define IDC_OPT_MOUSE                   1345
#define IDC_OPT_SCROLL                  1346
#define IDC_OPT_PAGE                    1347
#define IDC_OPT_IMPORT                  1348
#define IDC_OPT_SCALE                   1349
#define IDC_OPT_CONST                   1350
#define IDC_OTHER_ALL                   1351
#define IDC_OTHER_COLORS                1354
#define IDC_FONT_NAME                   1355
#define IDC_OTHER_ZOOM                  1355
#define IDC_PRP_Y                       1356
#define IDC_OTHER_MODE                  1356
#define IDC_PRP_Z                       1357
#define IDC_TARGET_X                    1358
#define IDC_TARGET_Y                    1359
#define IDC_TARGET_Z                    1360
#define IDC_CHECK32                     1360
#define IDC_OTHER_PROJ                  1360
#define IDC_FONT_PREVIEW                1360
#define IDC_PRP_X                       1361
#define IDC_RESET_ALL                   1361
#define IDC_VPN_X                       1362
#define IDC_VPN_Y                       1363
#define IDC_VPN_Z                       1364
#define IDC_HEIGHT                      1364
#define IDC_FONT                        1365
#define IDC_VUP_X                       1365
#define IDC_VUP_Y                       1366
#define IDC_VUP_Z                       1367
#define IDC_PRP_X2                      1368
#define IDC_DIAMETER                    1376
#define IDC_CENTERLINE                  1377
#define IDC_LOCAL_VIEWPOINT             1379
#define IDC_LIGHTING_ENABLED            1380
#define IDC_SEGMENT_TREE                1386
#define IDC_EXTRA_LIST_CTRL             1388
#define IDC_PENSTYLES                   1392
#define IDC_TRAP                        1393
#define IDC_TEXT                        1394
#define IDC_NORMAL                      1395
#define IDC_PAN                         1396
#define IDC_OVERVIEW                    1397
#define IDC_RATIO                       1398
#define IDC_ARCHITECTURAL               1399
#define IDC_ENGINEERING                 1400
#define IDC_FEET                        1401
#define IDC_INCHES                      1402
#define IDC_METRIC                      1403
#define IDC_PRECISION                   1404
#define IDC_TEXT_HEIGHT                 1405
#define IDC_TEXT_ROTATION               1406
#define IDC_PATH_RIGHT                  1407
#define IDC_PATH_LEFT                   1408
#define IDC_PATH_UP                     1409
#define IDC_PATH_DOWN                   1410
#define IDC_TEXT_EXP_FAC                1411
#define IDC_TEXT_SPACING                1412
#define IDC_TEXT_INCLIN                 1413
#define IDC_TEXT_ALIGN_HOR_LEFT         1414
#define IDC_TEXT_ALIGN_HOR_CEN          1415
#define IDC_TEXT_ALIGN_HOR_RIGHT        1416
#define IDC_TEXT_ALIGN_VER_BOT          1417
#define IDC_TEXT_ALIGN_VER_MID          1418
#define IDC_TEXT_ALIGN_VER_TOP          1419
#define IDC_ANGLE                       1420
#define IDC_TEXT_PREVIEW                1421
#define IDC_IMPORT_MODIFYFONT           1425
#define IDC_IMPORT_UNBLOCK              1426
#define IDC_IMPORT_PURGEBLOCKS          1427
#define IDC_IMPORT_KILLLAYERS           1428
#define IDC_IMPORT_OMITLAYERS           1429
#define IDC_IMPORT_COMMANDS             1430
#define IDC_IMPORT_HARDPENS             1431
#define IDC_IMPORT_SCALE                1432
#define IDC_IMPORT_TRANSLATE            1433
#define IDC_IMPORT_UNBLOCK2             1433
#define IDC_IDC_IMPORT_SCALE_VALUE      1434
#define IDC_IMPORT_SCALE_VALUE          1434
#define IDC_LIST1                       1436
#define IDC_IMPORT_TRANSLATELIST        1436
#define IDC_TRACING_LIST                1436
#define IDC_DRWG_REP                    1436
#define IDC_TRACING_PATH                1437
#define IDC_LIST2                       1437
#define IDC_HARDSTYLE                   1438
#define IDC_IMPORT_HARDSTYLE            1438
#define IDC_LIST3                       1438
#define IDC_COMBO1                      1439
#define IDC_LIST4                       1439
#define IDC_DRWG_REP_PRIMS              1439
#define IDC_ANN_ARR_TYP2                1439
#define IDC_TRANSPEN_OLD                1439
#define IDC_MOVE_LAYERS                 1439
#define IDC_TYPE_MARKER                 1439
#define IDC_IMPORT_POLYLINE             1439
#define IDC_INFO_COLOR1                 1439
#define IDC_BUTTON1                     1440
#define IDC_CLEAR_REG                   1440
#define IDC_TRANSPEN_NEW                1440
#define IDC_NBUF_CLEAR                  1440
#define IDC_COMBO2                      1440
#define IDC_INFO_COLOR2                 1440
#define IDC_CUSTOM1_UPDATE              1440
#define IDC_CLEAR_REG_ALL               1440
#define IDC_CLEAN_ALL                   1441
#define IDC_COMBO3                      1441
#define IDC_BUTTON2                     1441
#define IDC_INFO_COLOR3                 1441
#define IDC_TRANSPEN_OLD2               1441
#define IDC_BACK_COLOR                  1441
#define IDC_CUSTOM2_UPDATE              1441
#define IDC_TRANSTYLE_OLD               1441
#define IDC_CLEAR_REG2                  1441
#define IDC_CLEAN_STYLES                1442
#define IDC_COMBO4                      1442
#define IDC_BUTTON3                     1442
#define IDC_ORIGIN_COLOR1               1442
#define IDC_TRANSPEN_NEW2               1442
#define IDC_CUSTOM2_RENAME              1442
#define IDC_TRANSTYLE_NEW               1442
#define IDC_CLEAR_REG3                  1442
#define IDC_OPTIONS_TAB                 1443
#define IDC_COMBO5                      1443
#define IDC_BUTTON4                     1443
#define IDC_ORIGIN_COLOR2               1443
#define IDC_CUSTOM1_RENAME              1443
#define IDC_CLEAR_REG4                  1443
#define IDC_LIST5                       1444
#define IDC_DRWG_REP_PNT                1444
#define IDC_COMBO6                      1444
#define IDC_PENWIDTHS_FILE              1444
#define IDC_CUSTOM1_RENAME2             1444
#define IDC_CLEAR_REG5                  1444
#define IDC_LIST6                       1445
#define IDC_DRWG_REP_ATTR               1445
#define IDC_COLOR_FILE                  1445
#define IDC_CUSTOM1_RENAME3             1445
#define ID_REP_DELETE                   1446
#define IDC_ORIGIN_COLOR3               1446
#define IDC_QUERY_OLD                   1447
#define IDC_QUERY_NEW                   1448
#define IDC_FILL_HOLLOW1                1449
#define IDC_FILL_SOLID1                 1450
#define IDC_FILL_PATTERN1               1451
#define IDC_FILL_HATCH2                 1452
#define IDC_FILL_HATCH1                 1452
#define IDC_REM_DUP_SEG                 1455
#define IDC_REM_STY                     1456
#define IDC_REM_BLK                     1457
#define IDC_REM_LAY                     1458
#define IDC_REM_NOT                     1459
#define IDC_REM_EMP_SEG                 1460
#define IDC_STAT_COLOR                  1461
#define IDC_IRON_STATUS                 1461
#define IDC_DRAW2_WIDTH                 1462
#define IDC_FUSED_STATUS                1462
#define IDC_SETUP_TAB                   1463
#define IDC_IRON_STATUS2                1463
#define IDC_ZERO_STATUS                 1463
#define IDC_PRINT_TRANSLATELIST         1465
#define IDC_PP_TRANSLATELIST            1465
#define IDC_PP_PENWIDTH                 1466
#define IDC_PP_TRANSLATEPENS            1467
#define IDC_SCALE_USER                  1468
#define IDC_PP_HPGL                     1468
#define IDC_PP_TRANSLATELIST2           1468
#define IDC_WIDTH_FILE                  1468
#define IDC_BITMAP_PREVIEW              1469
#define IDC_PP_TRANSLATEPENS2           1469
#define IDC_TASKS_ALL                   1470
#define IDC_PP_TRANSLATELIST3           1470
#define IDC_PP_PENWIDTH2                1471
#define IDC_PRINT_PREVIEW               1472
#define IDC_WIDTH_FILE2                 1472
#define IDC_PP_PENWIDTH3                1473
#define IDC_PLOT_CLIP                   1473
#define IDC_USE_BORDER                  1474
#define IDC_ARCHIVE_STATIC              1475
#define IDC_NBUF_TEXT                   1476
#define IDC_ARCHIVE_STATIC2             1476
#define IDC_NBUF_GROUP                  1477
#define IDC_HEIGHT_TEXT                 1478
#define IDC_EXP_TEXT                    1479
#define IDC_ROTATION_TEXT               1480
#define IDC_SPACING_TEXT                1481
#define IDC_INC_TEXT                    1482
#define IDC_ALIGN_TEXT                  1483
#define IDC_HORZ_TEXT                   1484
#define IDC_VERT_TEXT                   1485
#define IDC_PATH_TEXT                   1486
#define IDC_PROGRESS1                   1487
#define IDC_CLEAN_PROGRESSBAR           1487
#define IDC_PROGRESS_BAR                1487
#define IDC_HEIGHT_TEXT2                1488
#define IDC_FONT_TEXT                   1488
#define IDC_STATIC_EYEX                 1488
#define IDC_STATIC_EYEY                 1489
#define IDC_STATIC_EYEZ                 1490
#define IDC_STATIC_TARGX                1491
#define IDC_STATIC_TARGY                1492
#define IDC_STATIC_TARGZ                1493
#define IDC_ENABLE_SHADOW               1494
#define IDC_READONLY                    1495
#define IDC_LAYOUT                      1495
#define ID_PRINTFILE                    1497
#define ID_PLOTFILE                     1498
#define IDC_CLIP_XMIN                   1499
#define IDC_CLIP_XMAX                   1500
#define IDC_CLIP_YMIN                   1501
#define IDC_CLIP_YMAX                   1502
#define IDC_ORIGIN_X                    1503
#define IDC_ORIGIN_Y                    1504
#define IDC_TREE1                       1505
#define IDC_HOTKEY1                     1506
#define IDC_DATETIMEPICKER1             1508
#define IDC_MONTHCALENDAR1              1509
#define IDC_CUSTOM1                     1510
#define IDC_PP_WIDTHLIST                1511
#define IDC_TREE2                       1512
#define IDC_SLIDER1                     1513
#define IDC_TRANS_SLIDER                1513
#define IDC_DISP_TTF                    1514
#define IDC_DISP_SCROLL                 1515
#define IDC_DISP_ODOM                   1516
#define IDC_PLOT_BUTTON                 1517
#define IDC_SOLO_DISCARD                1518
#define IDC_BCK_IMAGE                   1521
#define IDC_STAT_LAY                    1522
#define IDC_STAT_Y                      1523
#define IDC_STAT_X                      1524
#define IDC_STAT_YMAX                   1525
#define IDC_STAT_YMIN                   1526
#define IDC_STAT_XMAX                   1527
#define IDC_STAT_XMIN                   1528
#define IDC_STAT_ORIGIN                 1529
#define IDC_STAT_CLIP                   1530
#define IDC_PLOT_1                      1531
#define IDC_SHEET                       1531
#define IDC_PLOT_2                      1532
#define IDC_TRACING_PREVIEW             1532
#define IDC_PLOT_3                      1533
#define IDC_SOLO_SAVE                   1533
#define IDC_PLOT_4                      1534
#define IDC_PROGRESS_TEXT               1534
#define IDC_ORIGIN_STAT1                1535
#define IDC_ORIGIN_STAT2                1536
#define IDC_LAY2                        1537
#define IDC_TRA2                        1538
#define IDC_METRIC_UNITS2               1538
#define IDC_BLOCKS_LIST2                1539
#define IDC_DEFAULT_VIEW                1540
#define IDC_RECENT_DIR                  1541
#define IDC_UNIQUE                      1542
#define ID_TRACING_MVC                  1543
#define IDC_SOLOBMP_BUTTON              1544
#define IDC_BMPINCLUDE                  1544
#define IDC_XREFLIST                    1545
#define IDC_STOP_EDIT                   1546
#define ID_REMOVE_IMAGE                 1547
#define IDC_STOP_EDIT2                  1547
#define IDC_BITMAP_MELT                 1547
#define IDC_SHOW_HIDE                   1548
#define IDC_MOVE_POINT                  1549
#define IDC_DIM_CONST                   1549
#define IDC_ABB_DATE1                   1550
#define IDC_ABB_BUILD1                  1551
#define IDC_ABB_BUILD                   1552
#define IDS_OPENFILE_FILTER             3801
#define IDS_OPENFILE_FILTER_TRACINGS    3802
#define IDS_OPENFILE_FILTER_PENCOLORS   3803
#define IDS_OPENFILE_FILTER_APPS        3804
#define IDS_OPENFILE_FILTER_BLOCKS      3805
#define IDS_MSG_VERSION_1_JOB_FILE      3806
#define IDS_MSG_NO_DET_SEGS_IN_VIEW     3807
#define IDS_MSG_ZERO_LENGTH_STRING      3808
#define IDS_MSG_PRIM_ADDED_TO_DEL_SEGS  3809
#define IDS_SEG_DEL_TO_RESTORE          3810
#define IDS_MSG_BAD_PRIM_TYPE           3811
#define IDS_MSG_LAYER_IS_RESIDENT       3812
#define IDS_MSG_TRACING_WRITE_FAILURE   3813
#define IDS_MSG_TRACING_OPEN_FAILURE    3814
#define IDS_MSG_SQRT_NEG                3815
#define IDS_MSG_DDE_INIT_FAILURE        3816
#define IDS_MSG_LAYER_NO_STATIC         3817
#define IDS_MSG_LAYER_NO_HIDDEN         3818
#define IDS_MSG_LAYER_NO_ACTIVE         3819
#define IDS_MSG_CONFIRM_CLOSE           3820
#define IDS_MSG_CONFIRM_EXIT            3821
#define IDS_LAYER_NOT_LOADED            3822
#define IDS_MSG_CONFIRM_BLANK           3823
#define IDS_MSG_LAYER_NO_DELETE_0       3824
#define IDS_MSG_LAYER_NO_DELETE_WORK    3825
#define IDS_MSG_LAYER_NO_RENAME_0       3826
#define IDS_MSG_PTS_COINCIDE            3827
#define IDS_MSG_PTS_COLINEAR            3828
#define IDS_MSG_LPD_NO_END_CAP_LOC      3829
#define IDS_MSG_LPD_NOT_DUCT_SEC        3830
#define IDS_MSG_LPD_UNK_TURN_DIR        3831
#define IDS_MSG_MEM_ALLOC_ERR           3832
#define IDS_MSG_SAVE_STATE_LIST_ERROR   3833
#define IDS_MSG_FILE_LOCKED             3834
#define IDS_MSG_CLIPBOARD_LOCKED        3835
#define IDS_MSG_FILE_NOT_OPEN           3836
#define IDS_MSG_FILE_NOT_FOUND          3837
#define IDS_MSG_SAVE_CHANGES            3838
#define IDS_MSG_DISPOSE_FIRST           3839
#define IDS_MSG_CLOSE_TRACING_FIRST     3840
#define IDS_MSG_SHADOW_FILE_CREATE_FAILURE 3841
#define IDS_MSG_FILE_TYPE_ERROR         3842
#define IDS_MSG_FILE_NOT_A_TRACING      3843
#define IDS_MSG_OPEN_TRACING_NO_CLOAK   3844
#define IDS_MSG_NOTHING_TO_SAVE         3845
#define IDS_MSG_FILE_SHADOWED_AS        3846
#define IDS_MSG_TRACING_SAVE_SUCCESS    3847
#define IDS_MSG_TOO_MANY_PTS            3848
#define IDS_SUBPROC_PIPE_SYMBOL_NAMES   3849
#define IDS_HOME_POINT_GO_NAMES         3850
#define IDS_HOME_POINT_SET_NAMES        3851
#define IDS_OPENFILEFILTER_BITMAPS      3852
#define IDS_OPENFILE_FILTER_BITMAPS     3852
#define IDS_IMPORT_FILTER_DWG           3853
#define IDS_STRING3854                  3854
#define IDS_OPENFILE_FILTER_SAVEAS      3854
#define IDS_MSG_PEG_SAVE_SUCCESS        3855
#define IDS_MSG_DWG_SAVE_SUCCESS        3856
#define IDS_OPENFILE_FILTER_BROWSE      3857
#define IDS_IMPORT_FILTER_PEG           3858
#define IDS_MSG_RECOVER                 3859
#define IDS_MSG_LAYER_NO_MELT_0         3860
#define IDS_MSG_LAYER_NO_DUPS           3861
#define IDS_OPENFILE_FILTER_PEG2000     3862
#define IDS_OPENFILE_FILTER_PEG         3862
#define IDS_MSG_CONFIRM_DELETE          3863
#define IDS_MSG_XREF_NOTFOUND           3864
#define IDS_IMPORT_FILTER_PDF           3865
#define ID_MODE_ANNOTATE                32131
#define ID_MODE_CUT                     32132
#define ID_MODE_DIMENSION               32133
#define ID_MODE_DRAW                    32134
#define ID_MODE_DRAW2                   32135
#define ID_MODE_EDIT                    32136
#define ID_MODE_NODAL                   32137
#define ID_MODE_NODALR                  32138
#define ID_MODE_TRAP                    32139
#define ID_MODE_TRAPR                   32140
#define ID_MODE_FIXUP                   32141
#define ID_MODE_PRIM_EDIT               32142
#define ID_MODE_PRIM_MEND               32143
#define ID_MODE_SEG_EDIT                32144
#define ID_MODE_LPD                     32145
#define ID_MODE_POWER                   32146
#define ID_MODE_PIPE                    32147
#define ID_MODE_RLPD                    32148
#define ID_CURSOR_DEFAULT               32149
#define ID_MODE_EDIT2                   32149
#define ID_CURSOR_SYMBOL                32150
#define ID_SETUP_UNITS                  32151
#define ID_VIEW_REFRESH                 32152
#define ID_SETUP_SCALE                  32153
#define IDM_FILE_SAVE                   32154
#define IDM_FILE_CLOSE                  32155
#define IDM_FILE_OPEN                   32156
#define ID_SETUP_NOTE                   32158
#define ID_RELATIVEMOVES_RIGHT          32159
#define ID_RELATIVEMOVES_UP             32160
#define ID_RELATIVEMOVES_LEFT           32161
#define ID_RELATIVEMOVES_DOWN           32162
#define ID_RELATIVEMOVES_IN             32167
#define ID_RELATIVEMOVES_OUT            32168
#define ID_RELATIVEMOVES_RIGHTROTATE    32169
#define ID_RELATIVEMOVES_UPROTATE       32170
#define ID_RELATIVEMOVES_LEFTROTATE     32171
#define ID_RELATIVEMOVES_DOWNROTATE     32172
#define ID_SEG_DELETE                   32173
#define ID_PRIM_SNAPTO                  32174
#define ID_PRIM_SNAPTOENDPOINT          32175
#define ID_SEG_INSERT                   32177
#define ID_SETUP_PENCOLOR               32179
#define ID_SETUP_DIMLENGTH              32182
#define ID_SETUP_DIMANGLE               32183
#define ID_SETUP_PENSTYLE               32184
#define ID_OP0                          32186
#define ID_OP1                          32187
#define ID_OP2                          32188
#define ID_OP3                          32189
#define ID_OP4                          32190
#define ID_OP5                          32191
#define ID_OP6                          32192
#define ID_OP7                          32193
#define ID_OP8                          32194
#define ID_OP9                          32195
#define IDM_RETURN                      32196
#define IDM_ESCAPE                      32197
#define IDI_PEGAESYS                    32224
#define IDM_FILE_NEW                    32252
#define ID_SEG_BREAK                    32254
#define ID_PRIM_BREAK                   32255
#define ID_PENS_REMOVEUNUSEDSTYLES      32260
#define ID_PENS_LOADCOLORS              32261
#define ID_PENS_UNLOADCOLORS            32262
#define ID_PENS_TRANSLATE               32263
#define ID_LAYERS_LOAD                  32265
#define ID_LAYERS_UNLOAD                32266
#define ID_LAYERS_STATICALL             32268
#define ID_LAYERS_ACTIVEALL             32269
#define ID_BLOCKS_REMOVEUNUSED          32273
#define ID_PENS_EDITSTYLES              32274
#define ID_TRACINGS_MAPALL              32276
#define ID_TRACINGS_VIEWALL             32277
#define ID_TRACINGS_CLOAKALL            32278
#define ID_PENS_EDITCOLORS              32279
#define ID_PENS_USEDEFAULTS             32280
#define ID_SETUP_SAVEPOINT              32302
#define ID_SETUP_GOTOPOINT              32303
#define ID_FILE_PLOT_QUARTER            32304
#define ID_VIEW_BACKGROUNDIMAGE         32305
#define ID_MAINTENANCE_REMOVEDUPLICATES 32308
#define ID_MAINTENANCE_REMOVEEMPTYNOTES 32311
#define ID_MAINTENANCE_REMOVEEMPTYSEGMENTS 32312
#define IDB_BITMAP1                     32317
#define ID_FILE                         32319
#define ID_HELP_CONTENTS                32321
#define ID_CLEAR_VIEWEDTRACINGS         32322
#define ID_CLEAR_WORKINGLAYER           32323
#define ID_CLEAR_MAPPEDTRACINGS         32324
#define ID_RESET_ALL                    32325
#define ID_SETUP_FILL_HOLLOW            32326
#define ID_SETUP_FILL_SOLID             32327
#define ID_SETUP_FILL_PATTERN           32328
#define ID_SETUP_FILL_HATCH             32329
#define ID_PRIM_GOTOCENTERPOINT         32334
#define ID_MODE_REVISE                  32335
#define ID_MODE_LETTER                  32336
#define ID_PRIM_PERPJUMP                32337
#define ID_PRIM_MODIFY_ATTRIBUTES       32338
#define ID_HELP_KEY                     32339
#define ID_FILE_PRINTCURRENTVIEW        32341
#define ID_VIEW_ODOMETER                32342
#define ID_3DVIEWS_TOP                  32344
#define ID_3DVIEWS_BOTTOM               32345
#define ID_3DVIEWS_FRONT                32346
#define ID_3DVIEWS_BACK                 32347
#define ID_3DVIEWS_LEFT                 32348
#define ID_3DVIEWS_RIGHT                32349
#define ID_3DVIEWS_ISOMETRIC            32352
#define ID_3DVIEWS_AXONOMETRIC          32353
#define ID_3DVIEWS_OBLIQUE              32354
#define ID_3DVIEWS_PERSPECTIVE          32355
#define ID_VIEW_WIREFRAME               32356
#define ID_SEG_DELETELAST               32376
#define ID_PRIM_EXTRACTNUM              32377
#define ID_PRIM_EXTRACTSTR              32378
#define ID_EDIT_TRAPCOPY                32380
#define ID_EDIT_TRAPCUT                 32381
#define ID_EDIT_TRAPPASTE               32382
#define ID_MODE_SEGEDIT                 32388
#define ID_FILE_EXIT                    32394
#define ID_VIEW_RENDERED                32408
#define ID_VIEW_SOLID                   32409
#define ID_PRIM_DELETE                  32417
#define ID_VIEW_PARAMETERS              32436
#define ID_EDIT_IMAGETOCLIPBOARD        32438
#define ID_EDIT_TRACE                   32440
#define ID_SETUP_MOUSEBUTTONS           32450
#define ID_CURSOR_CROSSHAIR             32451
#define ID_SETUP_OPTIONS_DRAW           32508
#define ID_SETUP_OPTIONS_ANNOTATE       32510
#define ID_SETUP_OPTIONS_2LINE          32511
#define ID_SETUP_OPTIONS_FIXUP          32512
#define ID_SETUP_OPTIONS_DIMENSION      32513
#define ID_WINDOW_PAN_LEFT              32530
#define ID_WINDOW_PAN_UP                32532
#define ID_WINDOW_PAN_DOWN              32533
#define ID_VIEW_ZOOM                    32550
#define ID_WINDOW_ZOOMIN                32551
#define ID_WINDOW_ZOOMOUT               32552
#define ID_WINDOW_NORMAL                32553
#define ID_WINDOW_PAN                   32554
#define ID_TRACING_MAP                  32556
#define ID_TRACING_VIEW                 32557
#define ID_TRACING_CLOAK                32558
#define ID_TRACING_FUSE                 32559
#define ID_LAYER_WORK                   32560
#define ID_LAYER_ACTIVE                 32561
#define ID_LAYER_STATIC                 32562
#define ID_LAYER_HIDDEN                 32563
#define ID_LAYER_MELT                   32564
#define ID_LAYER_LAYERNAME              32565
#define ID_TRACING_TRACINGNAME          32566
#define ID_TRACING_OPEN                 32567
#define ID_EDIT_TRAPQUIT                32569
#define ID_FILE_PLOT_HALF               32571
#define ID_EDIT_TRAPWORK                32572
#define ID_EDIT_TRAPWORKANDACTIVE       32574
#define ID_TRAPCOMMANDS_ADDSEGMENTS     32575
#define ID_EDIT_TRAPDELETE              32577
#define ID_FILE_PLOT_FULL               32579
#define ID_TRAPCOMMANDS_HIGHLIGHT       32580
#define ID_TRAPCOMMANDS_COMPRESS        32581
#define ID_TRAPCOMMANDS_EXPAND          32582
#define ID_TRAPCOMMANDS_INVERT          32583
#define ID_TRAPCOMMANDS_SQUARE          32584
#define ID_TRAPCOMMANDS_QUERY           32585
#define ID_TRAPCOMMANDS_FILTER          32586
#define IDM_FILE_MANAGE                 32587
#define ID_TRAPCOMMANDS_BLOCK           32588
#define ID_TRAPCOMMANDS_UNBLOCK         32590
#define ID_SEG_EXCHANGE                 32591
#define ID_EDIT_SEGTOWORK               32593
#define ID_VIEW_PENWIDTHS               32594
#define ID_SETUP_CONSTRAINTS_AXIS       32599
#define ID_SETUP_CONSTRAINTS_GRID       32600
#define ID_VIEW_TRUETYPEFONTS           32605
#define ID_VIEW_STATEINFORMATION        32606
#define ID_CLEAR_ACTIVELAYERS           32607
#define ID_CLEAR_ALLLAYERS              32608
#define ID_CLEAR_ALLTRACINGS            32609
#define ID_EDIT_CF_SEGMENTS             32616
#define ID_EDIT_CF_TEXT                 32618
#define ID_EDIT_CF_IMAGE                32619
#define ID_VIEW_LIGHTING                32621
#define ID_WINDOW_PAN_RIGHT             32623
#define ID_WINDOW_BEST                  32624
#define ID_VIEW_WINDOW                  32625
#define ID_WINDOW_LAST                  32626
#define ID_WINDOW_SHEET                 32627
#define ID_CAMERA_ROTATELEFT            32629
#define ID_CAMERA_ROTATERIGHT           32630
#define ID_CAMERA_ROTATEUP              32631
#define ID_CAMERA_ROTATEDOWN            32632
#define ID_FILE_QUERY                   32666
#define ID_FILE_SHEETSETUP              32667
#define ID_SHEETSETUP_BACKGROUNDIMAGE   32668
#define ID_BACKGROUNDIMAGE_LOAD         32669
#define ID_BACKGROUNDIMAGE_REMOVE       32670
#define ID_RELATIVEMOVES_ENG_DOWN       32671
#define ID_RELATIVEMOVES_ENG_LEFT       32673
#define ID_RELATIVEMOVES_ENG_RIGHT      32674
#define ID_RELATIVEMOVES_ENG_UP         32675
#define ID_RELATIVEMOVES_ENG_IN         32677
#define ID_RELATIVEMOVES_ENG_OUT        32678
#define ID_RELATIVEMOVES_ENG_LEFTROTATE 32679
#define ID_RELATIVEMOVES_ENG_UPROTATE   32680
#define ID_RELATIVEMOVES_ENG_RIGHTROTATE 32681
#define ID_RELATIVEMOVES_ENG_DOWNROTATE 32683
#define ID_LAYERS_REMOVEEMPTY           32685
#define ID_SHEETSETUP_FORMFACTOR        32686
#define ID_VIEW_MODEINFORMATION         32687
#define ID_APP_ABOUT                    32688
#define ID_SHIFT_RETURN                 32689
#define ID_FILE_MRU1                    32692
#define ID_FILE_MRU2                    32693
#define ID_FILE_MRU3                    32694
#define ID_FILE_MRU4                    32695
#define ID_FILE_MRU5                    32696
#define ID_FILE_IMPORT                  32699
#define ID_IMPORT_DWG                   32701
#define ID_IMPORT_BMP                   32703
#define ID_IMPORT_PDF                   32704
#define ID_SETUP_IMPORT                 32705
#define ID_FILE_KK                      32706
#define ID_MAINTENANCE_IRON             32708
#define ID_CLEAR_ALL                    32709
#define ID__H                           32710
#define ID_Menu                         32716
#define ID_TRAPCOMMANDS_QUERY2          32719
#define ID_VIEW_SCROLLBARS              32721
#define ID_FILE_CLEAN                   32722
#define ID_TOOLS_OPTIONS                32723
#define ID_SETUP_UNUSED                 32725
#define IDM_FILE_SAVEAS                 32729
#define ID_SETUP_OPTIONS_EDIT           32731
#define ID_FILE_RUN                     32732
#define ID_FILE_EXPORT                  32733
#define ID_SETUP                        32736
#define ID_FILE_PRINTPREVIEW            32737
#define ID_VIEW_PRINTPREVIEW            32739
#define ID_ACCELERATOR32741             32741
#define ID_RESET_CUSTOM                 32742
#define ID_RESET_SETUP                  32743
#define ID_VIEW_CLIP                    32744
#define IDT_DRAW                        32745
#define IDT_ANNOTATE                    32746
#define ID_BUTTON32747                  32747
#define IDT_TRAP2                       32747
#define IDT_EDIT                        32748
#define IDT_DRAW2                       32749
#define IDT_DIMENSION                   32750
#define IDT_CUTUP                       32751
#define IDT_NODAL                       32752
#define ID_BUTTON32753                  32753
#define IDT_FIXUP                       32753
#define IDT_LPD                         32754
#define IDT_POWER                       32755
#define IDT_PIPE                        32756
#define IDT_RLPD                        32757
#define ID_VIEW_TOOLBAR                 32758
#define ID_BUTTON32759                  32759
#define IDT_DOCK                        32759
#define ID_MODE_DOCK                    32760
#define ID_FILE_ARCHIVE                 32762
#define ID_PRIM_GET_ATTRIBUTES          32763
#define ID_UNDO                         32765
#define ID_VIEW_INFORMATIONTOGGLE       32766
#define ID_EXPORT_DWG                   32767
#define ID_LAYERS_HIDEALL               32768
#define ID_ACCELERATOR32769             32769
#define ID_VIEW_HPGLPLOTTER             32771
#define ID_TRAPCOMMANDS_VECTORIZE       32774
#define ID_ACCELERATOR32775             32775
#define ID_CLIP_SET                     32775
#define ID_IMPORT_PEG                   32777
#define ID_PROFILES_CLASSIC             32779
#define ID_PROFILES_NEW                 32780
#define ID_PROFILES_CUSTOM1             32781
#define ID_PROFILES_CUSTOM2             32782
#define ID_FILE_TRACING                 32784
#define ID_EXPORT_PEG2000               32785
#define ID_FILE_PLOT                    32786
#define ID_ACTIVE_ALL                   32790
#define ID_STATIC_ALL                   32792
#define ID_PROFILES_MANAGER             32795
#define ID_IMPORT_SPREADSHEET           32799
#define ID_VIEW_LAYERSBYCOLOR           32801
#define ID_OP7_CTRL                     32802
#define ID_OP8_CTRL                     32803
#define ID_OP2_CTRL                     32804
#define ID_OP3_CTRL                     32805
#define ID_FILE_RECOVER                 32807
#define ID_LAYER_TOACTIVE               32813
#define ID_LAYER_TOSTATIC               32814
#define ID_LAYER_TOHIDDEN               32815
#define ID_TRA_TOMAP                    32816
#define ID_TRA_TOCLOAK                  32819
#define ID_TRA_TOVIEW                   32820
#define ID_LAYER_WASH                   32822
#define ID_SETUP_AUTOSAVE               32823
#define IDD_PRINTPREVIEW2               32824
#define ID_IMPORT_PORTABLEDOCUMENTFORMAT 32824
#define ID_IMPORT_RASTERTOVECTOR        32825
#define ID_CAMERA_ZROT_LEFT             32826
#define ID_CAMERA_ZROT_RIGHT            32827
#define ID_BITMAP_EDIT                  32828
#define ID_BACKGROUNDIMAGE_EDIT         32829
#define ID_MODE_BACKGROUNDEDIT          32830
#define ID_CAMERA_ROTATECLOCKWISE       32831
#define ID_CAMERA_ROTATECOUNTER         32832
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        235
#define _APS_NEXT_COMMAND_VALUE         32833
#define _APS_NEXT_CONTROL_VALUE         1553
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
